name: Meg Culp
favicon: null
layout_spectrum: 0.98685
typography_spectrum: 0.0025
title: Megs Vibes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c191d'
    - '#5ea4ce'
    - '#365663'
    - '#81d7e9'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
