title: "Vibin' with Meg"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#0B090A'
    - '#CECFD3'
    - '#455F82'
    - '#A0ACBA'
    - '#6D90A6'
  rhythmicContrast: 0.6577061
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Meg Culp
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
layout_spectrum: 1
