name: Meg Culp
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Megs Vibes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c191d'
    - '#5ea4ce'
    - '#365663'
    - '#81d7e9'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
